// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ca.proto

#ifndef PROTOBUF_ca_2eproto__INCLUDED
#define PROTOBUF_ca_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006002 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace proto {
namespace ca {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ca_2eproto();
void protobuf_AssignDesc_ca_2eproto();
void protobuf_ShutdownFile_ca_2eproto();

class csr_push;
class cert_push;
class push_ok;
class cert_pull;
class csr_pull;
class csr_pendding;
class csr_pendding_list;

// ===================================================================

class csr_push : public ::google::protobuf::Message {
 public:
  csr_push();
  virtual ~csr_push();

  csr_push(const csr_push& from);

  inline csr_push& operator=(const csr_push& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline csr_push& operator=(csr_push&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  csr_push(csr_push&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const csr_push& default_instance();

  void Swap(csr_push* other);

  // implements Message ----------------------------------------------

  csr_push* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const csr_push& from);
  void MergeFrom(const csr_push& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes fingerprint = 1;
  inline bool has_fingerprint() const;
  inline void clear_fingerprint();
  static const int kFingerprintFieldNumber = 1;
  inline const ::std::string& fingerprint() const;
  inline void set_fingerprint(const ::std::string& value);
  inline void set_fingerprint(const char* value);
  inline void set_fingerprint(const void* value, size_t size);
  inline ::std::string* mutable_fingerprint();
  inline ::std::string* release_fingerprint();
  inline void set_allocated_fingerprint(::std::string* fingerprint);

  // required bytes csr = 2;
  inline bool has_csr() const;
  inline void clear_csr();
  static const int kCsrFieldNumber = 2;
  inline const ::std::string& csr() const;
  inline void set_csr(const ::std::string& value);
  inline void set_csr(const char* value);
  inline void set_csr(const void* value, size_t size);
  inline ::std::string* mutable_csr();
  inline ::std::string* release_csr();
  inline void set_allocated_csr(::std::string* csr);

  // @@protoc_insertion_point(class_scope:proto.ca.csr_push)
 private:
  inline void set_has_fingerprint();
  inline void clear_has_fingerprint();
  inline void set_has_csr();
  inline void clear_has_csr();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* fingerprint_;
  ::std::string* csr_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static csr_push* default_instance_;
};
// -------------------------------------------------------------------

class cert_push : public ::google::protobuf::Message {
 public:
  cert_push();
  virtual ~cert_push();

  cert_push(const cert_push& from);

  inline cert_push& operator=(const cert_push& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline cert_push& operator=(cert_push&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  cert_push(cert_push&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cert_push& default_instance();

  void Swap(cert_push* other);

  // implements Message ----------------------------------------------

  cert_push* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cert_push& from);
  void MergeFrom(const cert_push& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes fingerprint = 1;
  inline bool has_fingerprint() const;
  inline void clear_fingerprint();
  static const int kFingerprintFieldNumber = 1;
  inline const ::std::string& fingerprint() const;
  inline void set_fingerprint(const ::std::string& value);
  inline void set_fingerprint(const char* value);
  inline void set_fingerprint(const void* value, size_t size);
  inline ::std::string* mutable_fingerprint();
  inline ::std::string* release_fingerprint();
  inline void set_allocated_fingerprint(::std::string* fingerprint);

  // required bytes cert = 2;
  inline bool has_cert() const;
  inline void clear_cert();
  static const int kCertFieldNumber = 2;
  inline const ::std::string& cert() const;
  inline void set_cert(const ::std::string& value);
  inline void set_cert(const char* value);
  inline void set_cert(const void* value, size_t size);
  inline ::std::string* mutable_cert();
  inline ::std::string* release_cert();
  inline void set_allocated_cert(::std::string* cert);

  // @@protoc_insertion_point(class_scope:proto.ca.cert_push)
 private:
  inline void set_has_fingerprint();
  inline void clear_has_fingerprint();
  inline void set_has_cert();
  inline void clear_has_cert();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* fingerprint_;
  ::std::string* cert_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static cert_push* default_instance_;
};
// -------------------------------------------------------------------

class push_ok : public ::google::protobuf::Message {
 public:
  push_ok();
  virtual ~push_ok();

  push_ok(const push_ok& from);

  inline push_ok& operator=(const push_ok& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline push_ok& operator=(push_ok&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  push_ok(push_ok&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const push_ok& default_instance();

  void Swap(push_ok* other);

  // implements Message ----------------------------------------------

  push_ok* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const push_ok& from);
  void MergeFrom(const push_ok& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated bytes fingerprints = 1;
  inline int fingerprints_size() const;
  inline void clear_fingerprints();
  static const int kFingerprintsFieldNumber = 1;
  inline const ::std::string& fingerprints(int index) const;
  inline ::std::string* mutable_fingerprints(int index);
  inline void set_fingerprints(int index, const ::std::string& value);
  inline void set_fingerprints(int index, const char* value);
  inline void set_fingerprints(int index, const void* value, size_t size);
  inline ::std::string* add_fingerprints();
  inline void add_fingerprints(const ::std::string& value);
  inline void add_fingerprints(const char* value);
  inline void add_fingerprints(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& fingerprints() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_fingerprints();

  // @@protoc_insertion_point(class_scope:proto.ca.push_ok)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> fingerprints_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static push_ok* default_instance_;
};
// -------------------------------------------------------------------

class cert_pull : public ::google::protobuf::Message {
 public:
  cert_pull();
  virtual ~cert_pull();

  cert_pull(const cert_pull& from);

  inline cert_pull& operator=(const cert_pull& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline cert_pull& operator=(cert_pull&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  cert_pull(cert_pull&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const cert_pull& default_instance();

  void Swap(cert_pull* other);

  // implements Message ----------------------------------------------

  cert_pull* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const cert_pull& from);
  void MergeFrom(const cert_pull& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes fingerprint = 1;
  inline bool has_fingerprint() const;
  inline void clear_fingerprint();
  static const int kFingerprintFieldNumber = 1;
  inline const ::std::string& fingerprint() const;
  inline void set_fingerprint(const ::std::string& value);
  inline void set_fingerprint(const char* value);
  inline void set_fingerprint(const void* value, size_t size);
  inline ::std::string* mutable_fingerprint();
  inline ::std::string* release_fingerprint();
  inline void set_allocated_fingerprint(::std::string* fingerprint);

  // @@protoc_insertion_point(class_scope:proto.ca.cert_pull)
 private:
  inline void set_has_fingerprint();
  inline void clear_has_fingerprint();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* fingerprint_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static cert_pull* default_instance_;
};
// -------------------------------------------------------------------

class csr_pull : public ::google::protobuf::Message {
 public:
  csr_pull();
  virtual ~csr_pull();

  csr_pull(const csr_pull& from);

  inline csr_pull& operator=(const csr_pull& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline csr_pull& operator=(csr_pull&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  csr_pull(csr_pull&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const csr_pull& default_instance();

  void Swap(csr_pull* other);

  // implements Message ----------------------------------------------

  csr_pull* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const csr_pull& from);
  void MergeFrom(const csr_pull& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required bytes fingerprint = 1;
  inline bool has_fingerprint() const;
  inline void clear_fingerprint();
  static const int kFingerprintFieldNumber = 1;
  inline const ::std::string& fingerprint() const;
  inline void set_fingerprint(const ::std::string& value);
  inline void set_fingerprint(const char* value);
  inline void set_fingerprint(const void* value, size_t size);
  inline ::std::string* mutable_fingerprint();
  inline ::std::string* release_fingerprint();
  inline void set_allocated_fingerprint(::std::string* fingerprint);

  // @@protoc_insertion_point(class_scope:proto.ca.csr_pull)
 private:
  inline void set_has_fingerprint();
  inline void clear_has_fingerprint();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* fingerprint_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static csr_pull* default_instance_;
};
// -------------------------------------------------------------------

class csr_pendding : public ::google::protobuf::Message {
 public:
  csr_pendding();
  virtual ~csr_pendding();

  csr_pendding(const csr_pendding& from);

  inline csr_pendding& operator=(const csr_pendding& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline csr_pendding& operator=(csr_pendding&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  csr_pendding(csr_pendding&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const csr_pendding& default_instance();

  void Swap(csr_pendding* other);

  // implements Message ----------------------------------------------

  csr_pendding* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const csr_pendding& from);
  void MergeFrom(const csr_pendding& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:proto.ca.csr_pendding)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static csr_pendding* default_instance_;
};
// -------------------------------------------------------------------

class csr_pendding_list : public ::google::protobuf::Message {
 public:
  csr_pendding_list();
  virtual ~csr_pendding_list();

  csr_pendding_list(const csr_pendding_list& from);

  inline csr_pendding_list& operator=(const csr_pendding_list& from) {
    CopyFrom(from);
    return *this;
  }

  #if __cplusplus >= 201103L || _MSC_VER >= 1600
  inline csr_pendding_list& operator=(csr_pendding_list&& from) {
    if (&from != this) {
      Clear();
      Swap(&from);
    }
    return *this;
  }

  csr_pendding_list(csr_pendding_list&& from);
  #endif

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const csr_pendding_list& default_instance();

  void Swap(csr_pendding_list* other);

  // implements Message ----------------------------------------------

  csr_pendding_list* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const csr_pendding_list& from);
  void MergeFrom(const csr_pendding_list& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 num = 1;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 1;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // repeated bytes fingerprint = 2;
  inline int fingerprint_size() const;
  inline void clear_fingerprint();
  static const int kFingerprintFieldNumber = 2;
  inline const ::std::string& fingerprint(int index) const;
  inline ::std::string* mutable_fingerprint(int index);
  inline void set_fingerprint(int index, const ::std::string& value);
  inline void set_fingerprint(int index, const char* value);
  inline void set_fingerprint(int index, const void* value, size_t size);
  inline ::std::string* add_fingerprint();
  inline void add_fingerprint(const ::std::string& value);
  inline void add_fingerprint(const char* value);
  inline void add_fingerprint(const void* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& fingerprint() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_fingerprint();

  // @@protoc_insertion_point(class_scope:proto.ca.csr_pendding_list)
 private:
  inline void set_has_num();
  inline void clear_has_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> fingerprint_;
  ::google::protobuf::uint32 num_;
  friend void  protobuf_AddDesc_ca_2eproto();
  friend void protobuf_AssignDesc_ca_2eproto();
  friend void protobuf_ShutdownFile_ca_2eproto();

  void InitAsDefaultInstance();
  static csr_pendding_list* default_instance_;
};
// ===================================================================


// ===================================================================

// csr_push

// required bytes fingerprint = 1;
inline bool csr_push::has_fingerprint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void csr_push::set_has_fingerprint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void csr_push::clear_has_fingerprint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void csr_push::clear_fingerprint() {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_->clear();
  }
  clear_has_fingerprint();
}
inline const ::std::string& csr_push::fingerprint() const {
  // @@protoc_insertion_point(field_get:proto.ca.csr_push.fingerprint)
  return *fingerprint_;
}
inline void csr_push::set_fingerprint(const ::std::string& value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set:proto.ca.csr_push.fingerprint)
}
inline void csr_push::set_fingerprint(const char* value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.csr_push.fingerprint)
}
inline void csr_push::set_fingerprint(const void* value, size_t size) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.csr_push.fingerprint)
}
inline ::std::string* csr_push::mutable_fingerprint() {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.ca.csr_push.fingerprint)
  return fingerprint_;
}
inline ::std::string* csr_push::release_fingerprint() {
  clear_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = fingerprint_;
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void csr_push::set_allocated_fingerprint(::std::string* fingerprint) {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete fingerprint_;
  }
  if (fingerprint) {
    set_has_fingerprint();
    fingerprint_ = fingerprint;
  } else {
    clear_has_fingerprint();
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ca.csr_push.fingerprint)
}

// required bytes csr = 2;
inline bool csr_push::has_csr() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void csr_push::set_has_csr() {
  _has_bits_[0] |= 0x00000002u;
}
inline void csr_push::clear_has_csr() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void csr_push::clear_csr() {
  if (csr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    csr_->clear();
  }
  clear_has_csr();
}
inline const ::std::string& csr_push::csr() const {
  // @@protoc_insertion_point(field_get:proto.ca.csr_push.csr)
  return *csr_;
}
inline void csr_push::set_csr(const ::std::string& value) {
  set_has_csr();
  if (csr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    csr_ = new ::std::string;
  }
  csr_->assign(value);
  // @@protoc_insertion_point(field_set:proto.ca.csr_push.csr)
}
inline void csr_push::set_csr(const char* value) {
  set_has_csr();
  if (csr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    csr_ = new ::std::string;
  }
  csr_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.csr_push.csr)
}
inline void csr_push::set_csr(const void* value, size_t size) {
  set_has_csr();
  if (csr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    csr_ = new ::std::string;
  }
  csr_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.csr_push.csr)
}
inline ::std::string* csr_push::mutable_csr() {
  set_has_csr();
  if (csr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    csr_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.ca.csr_push.csr)
  return csr_;
}
inline ::std::string* csr_push::release_csr() {
  clear_has_csr();
  if (csr_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = csr_;
    csr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void csr_push::set_allocated_csr(::std::string* csr) {
  if (csr_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete csr_;
  }
  if (csr) {
    set_has_csr();
    csr_ = csr;
  } else {
    clear_has_csr();
    csr_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ca.csr_push.csr)
}

// -------------------------------------------------------------------

// cert_push

// required bytes fingerprint = 1;
inline bool cert_push::has_fingerprint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cert_push::set_has_fingerprint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cert_push::clear_has_fingerprint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cert_push::clear_fingerprint() {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_->clear();
  }
  clear_has_fingerprint();
}
inline const ::std::string& cert_push::fingerprint() const {
  // @@protoc_insertion_point(field_get:proto.ca.cert_push.fingerprint)
  return *fingerprint_;
}
inline void cert_push::set_fingerprint(const ::std::string& value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set:proto.ca.cert_push.fingerprint)
}
inline void cert_push::set_fingerprint(const char* value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.cert_push.fingerprint)
}
inline void cert_push::set_fingerprint(const void* value, size_t size) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.cert_push.fingerprint)
}
inline ::std::string* cert_push::mutable_fingerprint() {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.ca.cert_push.fingerprint)
  return fingerprint_;
}
inline ::std::string* cert_push::release_fingerprint() {
  clear_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = fingerprint_;
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void cert_push::set_allocated_fingerprint(::std::string* fingerprint) {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete fingerprint_;
  }
  if (fingerprint) {
    set_has_fingerprint();
    fingerprint_ = fingerprint;
  } else {
    clear_has_fingerprint();
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ca.cert_push.fingerprint)
}

// required bytes cert = 2;
inline bool cert_push::has_cert() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void cert_push::set_has_cert() {
  _has_bits_[0] |= 0x00000002u;
}
inline void cert_push::clear_has_cert() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void cert_push::clear_cert() {
  if (cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cert_->clear();
  }
  clear_has_cert();
}
inline const ::std::string& cert_push::cert() const {
  // @@protoc_insertion_point(field_get:proto.ca.cert_push.cert)
  return *cert_;
}
inline void cert_push::set_cert(const ::std::string& value) {
  set_has_cert();
  if (cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cert_ = new ::std::string;
  }
  cert_->assign(value);
  // @@protoc_insertion_point(field_set:proto.ca.cert_push.cert)
}
inline void cert_push::set_cert(const char* value) {
  set_has_cert();
  if (cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cert_ = new ::std::string;
  }
  cert_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.cert_push.cert)
}
inline void cert_push::set_cert(const void* value, size_t size) {
  set_has_cert();
  if (cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cert_ = new ::std::string;
  }
  cert_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.cert_push.cert)
}
inline ::std::string* cert_push::mutable_cert() {
  set_has_cert();
  if (cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    cert_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.ca.cert_push.cert)
  return cert_;
}
inline ::std::string* cert_push::release_cert() {
  clear_has_cert();
  if (cert_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = cert_;
    cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void cert_push::set_allocated_cert(::std::string* cert) {
  if (cert_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete cert_;
  }
  if (cert) {
    set_has_cert();
    cert_ = cert;
  } else {
    clear_has_cert();
    cert_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ca.cert_push.cert)
}

// -------------------------------------------------------------------

// push_ok

// repeated bytes fingerprints = 1;
inline int push_ok::fingerprints_size() const {
  return fingerprints_.size();
}
inline void push_ok::clear_fingerprints() {
  fingerprints_.Clear();
}
inline const ::std::string& push_ok::fingerprints(int index) const {
  // @@protoc_insertion_point(field_get:proto.ca.push_ok.fingerprints)
  return fingerprints_.Get(index);
}
inline ::std::string* push_ok::mutable_fingerprints(int index) {
  // @@protoc_insertion_point(field_mutable:proto.ca.push_ok.fingerprints)
  return fingerprints_.Mutable(index);
}
inline void push_ok::set_fingerprints(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:proto.ca.push_ok.fingerprints)
  fingerprints_.Mutable(index)->assign(value);
}
inline void push_ok::set_fingerprints(int index, const char* value) {
  fingerprints_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.push_ok.fingerprints)
}
inline void push_ok::set_fingerprints(int index, const void* value, size_t size) {
  fingerprints_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.push_ok.fingerprints)
}
inline ::std::string* push_ok::add_fingerprints() {
  return fingerprints_.Add();
}
inline void push_ok::add_fingerprints(const ::std::string& value) {
  fingerprints_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:proto.ca.push_ok.fingerprints)
}
inline void push_ok::add_fingerprints(const char* value) {
  fingerprints_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:proto.ca.push_ok.fingerprints)
}
inline void push_ok::add_fingerprints(const void* value, size_t size) {
  fingerprints_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:proto.ca.push_ok.fingerprints)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
push_ok::fingerprints() const {
  // @@protoc_insertion_point(field_list:proto.ca.push_ok.fingerprints)
  return fingerprints_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
push_ok::mutable_fingerprints() {
  // @@protoc_insertion_point(field_mutable_list:proto.ca.push_ok.fingerprints)
  return &fingerprints_;
}

// -------------------------------------------------------------------

// cert_pull

// required bytes fingerprint = 1;
inline bool cert_pull::has_fingerprint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void cert_pull::set_has_fingerprint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void cert_pull::clear_has_fingerprint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void cert_pull::clear_fingerprint() {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_->clear();
  }
  clear_has_fingerprint();
}
inline const ::std::string& cert_pull::fingerprint() const {
  // @@protoc_insertion_point(field_get:proto.ca.cert_pull.fingerprint)
  return *fingerprint_;
}
inline void cert_pull::set_fingerprint(const ::std::string& value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set:proto.ca.cert_pull.fingerprint)
}
inline void cert_pull::set_fingerprint(const char* value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.cert_pull.fingerprint)
}
inline void cert_pull::set_fingerprint(const void* value, size_t size) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.cert_pull.fingerprint)
}
inline ::std::string* cert_pull::mutable_fingerprint() {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.ca.cert_pull.fingerprint)
  return fingerprint_;
}
inline ::std::string* cert_pull::release_fingerprint() {
  clear_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = fingerprint_;
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void cert_pull::set_allocated_fingerprint(::std::string* fingerprint) {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete fingerprint_;
  }
  if (fingerprint) {
    set_has_fingerprint();
    fingerprint_ = fingerprint;
  } else {
    clear_has_fingerprint();
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ca.cert_pull.fingerprint)
}

// -------------------------------------------------------------------

// csr_pull

// required bytes fingerprint = 1;
inline bool csr_pull::has_fingerprint() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void csr_pull::set_has_fingerprint() {
  _has_bits_[0] |= 0x00000001u;
}
inline void csr_pull::clear_has_fingerprint() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void csr_pull::clear_fingerprint() {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_->clear();
  }
  clear_has_fingerprint();
}
inline const ::std::string& csr_pull::fingerprint() const {
  // @@protoc_insertion_point(field_get:proto.ca.csr_pull.fingerprint)
  return *fingerprint_;
}
inline void csr_pull::set_fingerprint(const ::std::string& value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set:proto.ca.csr_pull.fingerprint)
}
inline void csr_pull::set_fingerprint(const char* value) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.csr_pull.fingerprint)
}
inline void csr_pull::set_fingerprint(const void* value, size_t size) {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  fingerprint_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.csr_pull.fingerprint)
}
inline ::std::string* csr_pull::mutable_fingerprint() {
  set_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    fingerprint_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:proto.ca.csr_pull.fingerprint)
  return fingerprint_;
}
inline ::std::string* csr_pull::release_fingerprint() {
  clear_has_fingerprint();
  if (fingerprint_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = fingerprint_;
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void csr_pull::set_allocated_fingerprint(::std::string* fingerprint) {
  if (fingerprint_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete fingerprint_;
  }
  if (fingerprint) {
    set_has_fingerprint();
    fingerprint_ = fingerprint;
  } else {
    clear_has_fingerprint();
    fingerprint_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:proto.ca.csr_pull.fingerprint)
}

// -------------------------------------------------------------------

// csr_pendding

// -------------------------------------------------------------------

// csr_pendding_list

// required uint32 num = 1;
inline bool csr_pendding_list::has_num() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void csr_pendding_list::set_has_num() {
  _has_bits_[0] |= 0x00000001u;
}
inline void csr_pendding_list::clear_has_num() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void csr_pendding_list::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 csr_pendding_list::num() const {
  // @@protoc_insertion_point(field_get:proto.ca.csr_pendding_list.num)
  return num_;
}
inline void csr_pendding_list::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
  // @@protoc_insertion_point(field_set:proto.ca.csr_pendding_list.num)
}

// repeated bytes fingerprint = 2;
inline int csr_pendding_list::fingerprint_size() const {
  return fingerprint_.size();
}
inline void csr_pendding_list::clear_fingerprint() {
  fingerprint_.Clear();
}
inline const ::std::string& csr_pendding_list::fingerprint(int index) const {
  // @@protoc_insertion_point(field_get:proto.ca.csr_pendding_list.fingerprint)
  return fingerprint_.Get(index);
}
inline ::std::string* csr_pendding_list::mutable_fingerprint(int index) {
  // @@protoc_insertion_point(field_mutable:proto.ca.csr_pendding_list.fingerprint)
  return fingerprint_.Mutable(index);
}
inline void csr_pendding_list::set_fingerprint(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:proto.ca.csr_pendding_list.fingerprint)
  fingerprint_.Mutable(index)->assign(value);
}
inline void csr_pendding_list::set_fingerprint(int index, const char* value) {
  fingerprint_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:proto.ca.csr_pendding_list.fingerprint)
}
inline void csr_pendding_list::set_fingerprint(int index, const void* value, size_t size) {
  fingerprint_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:proto.ca.csr_pendding_list.fingerprint)
}
inline ::std::string* csr_pendding_list::add_fingerprint() {
  return fingerprint_.Add();
}
inline void csr_pendding_list::add_fingerprint(const ::std::string& value) {
  fingerprint_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:proto.ca.csr_pendding_list.fingerprint)
}
inline void csr_pendding_list::add_fingerprint(const char* value) {
  fingerprint_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:proto.ca.csr_pendding_list.fingerprint)
}
inline void csr_pendding_list::add_fingerprint(const void* value, size_t size) {
  fingerprint_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:proto.ca.csr_pendding_list.fingerprint)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
csr_pendding_list::fingerprint() const {
  // @@protoc_insertion_point(field_list:proto.ca.csr_pendding_list.fingerprint)
  return fingerprint_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
csr_pendding_list::mutable_fingerprint() {
  // @@protoc_insertion_point(field_mutable_list:proto.ca.csr_pendding_list.fingerprint)
  return &fingerprint_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace ca
}  // namespace proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ca_2eproto__INCLUDED
